// backend/src/utils/errorCodes.ts

export enum ErrorCode {
INVALID_PHONE_PREFIX = 'INVALID_PHONE_PREFIX',
    // Langue utilisateur
LANGUAGE_REQUIRED = 'LANGUAGE_REQUIRED',
INVALID_LANGUAGE = 'INVALID_LANGUAGE',
LANGUAGE_UPDATE_FAILED = 'LANGUAGE_UPDATE_FAILED',
SUPPORTED_LANGUAGES_LOAD_FAILED = 'SUPPORTED_LANGUAGES_LOAD_FAILED',
    // Stripe Webhooks
WEBHOOK_SIGNATURE_INVALID = 'WEBHOOK_SIGNATURE_INVALID',
WEBHOOK_PROCESSING_FAILED = 'WEBHOOK_PROCESSING_FAILED',
    // Stripe Connect
STRIPE_CONNECT_NOT_AVAILABLE = 'STRIPE_CONNECT_NOT_AVAILABLE',
STRIPE_ONBOARDING_FAILED = 'STRIPE_ONBOARDING_FAILED',
STRIPE_STATUS_CHECK_FAILED = 'STRIPE_STATUS_CHECK_FAILED',
INVALID_COUNTRY_CODE = 'INVALID_COUNTRY_CODE',
COUNTRY_UPDATE_FAILED = 'COUNTRY_UPDATE_FAILED',
STRIPE_DISCONNECT_FAILED = 'STRIPE_DISCONNECT_FAILED',
PAYMENT_INFO_LOAD_FAILED = 'PAYMENT_INFO_LOAD_FAILED',
       // Notifications
NOTIFICATIONS_LOAD_FAILED = 'NOTIFICATIONS_LOAD_FAILED',
INVALID_NOTIFICATION_ID = 'INVALID_NOTIFICATION_ID',
NOTIFICATION_NOT_FOUND = 'NOTIFICATION_NOT_FOUND',
NOTIFICATION_UPDATE_FAILED = 'NOTIFICATION_UPDATE_FAILED',
FCM_TOKEN_REQUIRED = 'FCM_TOKEN_REQUIRED',
FCM_TOKEN_REGISTRATION_FAILED = 'FCM_TOKEN_REGISTRATION_FAILED',
NOTIFICATION_DELETE_FAILED = 'NOTIFICATION_DELETE_FAILED',
UNREAD_COUNT_FAILED = 'UNREAD_COUNT_FAILED',
CHAT_ID_REQUIRED = 'CHAT_ID_REQUIRED',
MARK_CHAT_READ_FAILED = 'MARK_CHAT_READ_FAILED',
    // Chat
  CONVERSATIONS_LOAD_FAILED = 'CONVERSATIONS_LOAD_FAILED',
  MESSAGES_LOAD_FAILED = 'MESSAGES_LOAD_FAILED',
  OTHER_USER_ID_REQUIRED = 'OTHER_USER_ID_REQUIRED',
  CANNOT_CHAT_WITH_SELF = 'CANNOT_CHAT_WITH_SELF',
  USER_NOT_AUTHORIZED_OR_NOT_FOUND = 'USER_NOT_AUTHORIZED_OR_NOT_FOUND',
  CONVERSATION_CREATION_FAILED = 'CONVERSATION_CREATION_FAILED',
  CONVERSATION_NOT_FOUND = 'CONVERSATION_NOT_FOUND',
  CONVERSATION_ARCHIVE_FAILED = 'CONVERSATION_ARCHIVE_FAILED',
  // Authentification
  UNAUTHORIZED = 'UNAUTHORIZED',
  FORBIDDEN = 'FORBIDDEN',
  INVALID_CREDENTIALS = 'INVALID_CREDENTIALS',
  TOKEN_EXPIRED = 'TOKEN_EXPIRED',  
  EMAIL_NOT_VERIFIED = 'EMAIL_NOT_VERIFIED',
  
  // Ressources introuvables
  TRANSACTION_NOT_FOUND = 'TRANSACTION_NOT_FOUND',
  USER_NOT_FOUND = 'USER_NOT_FOUND',
  TRIP_NOT_FOUND = 'TRIP_NOT_FOUND',
  REVIEW_NOT_FOUND = 'REVIEW_NOT_FOUND',
  
  // Validation
  TRANSACTION_NOT_COMPLETED = 'TRANSACTION_NOT_COMPLETED',
  REVIEW_ALREADY_EXISTS = 'REVIEW_ALREADY_EXISTS',
  PROFILE_NAME_LENGTH = 'PROFILE_NAME_LENGTH',
  PROFILE_NAME_ALREADY_USED = 'PROFILE_NAME_ALREADY_USED',
  INSUFFICIENT_BALANCE = 'INSUFFICIENT_BALANCE',
  INVALID_INPUT = 'INVALID_INPUT',
  EMAIL_ALREADY_EXISTS = 'EMAIL_ALREADY_EXISTS',
  
  // Serveur
  SERVER_ERROR = 'SERVER_ERROR',
  DATABASE_ERROR = 'DATABASE_ERROR',

  // Inscription
  MISSING_FIELDS = 'MISSING_FIELDS',
  EMAIL_ALREADY_USED = 'EMAIL_ALREADY_USED',
  VERIFICATION_CODE_SEND_FAILED = 'VERIFICATION_CODE_SEND_FAILED',
  // Vérification email
  VERIFICATION_CODE_REQUIRED = 'VERIFICATION_CODE_REQUIRED',  
  EMAIL_ALREADY_VERIFIED = 'EMAIL_ALREADY_VERIFIED',
  INVALID_VERIFICATION_CODE = 'INVALID_VERIFICATION_CODE',
  USER_NOT_FOUND_OR_VERIFIED = 'USER_NOT_FOUND_OR_VERIFIED',
  VERIFICATION_FAILED = 'VERIFICATION_FAILED',
  
  // Réinitialisation mot de passe
  EMAIL_REQUIRED = 'EMAIL_REQUIRED',
  TOKEN_AND_PASSWORD_REQUIRED = 'TOKEN_AND_PASSWORD_REQUIRED',
  INVALID_OR_EXPIRED_TOKEN = 'INVALID_OR_EXPIRED_TOKEN',
  
  // Changement mot de passe
  CURRENT_AND_NEW_PASSWORD_REQUIRED = 'CURRENT_AND_NEW_PASSWORD_REQUIRED',
  PASSWORD_TOO_SHORT = 'PASSWORD_TOO_SHORT',
  CURRENT_PASSWORD_INCORRECT = 'CURRENT_PASSWORD_INCORRECT',
  
  // Suppression compte
  NOT_AUTHENTICATED = 'NOT_AUTHENTICATED',
  ACTIVE_TRANSACTIONS_EXIST = 'ACTIVE_TRANSACTIONS_EXIST',
  NON_ZERO_WALLET_BALANCE = 'NON_ZERO_WALLET_BALANCE',
  
  // Stripe
  INVALID_POSTAL_CODE = 'INVALID_POSTAL_CODE',
  INVALID_PHONE = 'INVALID_PHONE',
  INVALID_ADDRESS = 'INVALID_ADDRESS',
  STATE_REQUIRED = 'STATE_REQUIRED',
  STRIPE_ACCOUNT_CREATION_FAILED = 'STRIPE_ACCOUNT_CREATION_FAILED',
}

// Helper pour retourner des erreurs standardisées
export const errorResponse = (code: ErrorCode) => {
  return {
    success: false,
    errorCode: code
  };
};

// Helper pour les succès
export const successResponse = (data?: any, message?: string) => {
  return {
    success: true,
    data,
    message: message || 'SUCCESS'
  };
};